<?php
/** @var $block \Digidennis\FabricColors\Block\Product\ColorJson */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
$colors  = $block->getColorData($product);
?>
<script>
    window.digidennisFabricColors = window.digidennisFabricColors || {};
    window.digidennisFabricColors[<?= (int)$product->getId() ?>] = <?= json_encode($colors) ?>;
</script>
